---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1t07ar7ldwv64ggxzqk2h2k96evdalecn6k4t9t5pek32nss97cnse646gk
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1t07ar7ldwv64ggxzqk2h2k96evdalecn6k4t9t5pek32nss97cnse646gk
