---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1sqp48282k0d302wl00gv72ka6z7p05we8e2cugnfwcypzqa5tyqqj92tsl
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1sqp48282k0d302wl00gv72ka6z7p05we8e2cugnfwcypzqa5tyqqj92tsl
