---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
namespace: cattle-system
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: https://releases.rancher.com/server-charts/stable
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: "video-input-antenna"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - host: "rancher.${SECRET_DOMAIN}"
          paths:
            - "/"
      tls:
        - secretName: rancher-tls
          hosts:
            - "rancher.${SECRET_DOMAIN}"
      args: --set hostname=rancher.${SECRET_DOMAIN} \
        --set bootstrapPassword=admin \
#    resources:
#      requests:
#        cpu: 50m
#        memory: 64Mi
#      limits:
#        memory: 96Mi
